pipeline {
    agent any
    stages {
        stage('Create Kubernetes Cluster using eksctl') {
            steps {
                withAWS(region:'us-east-1', credentials: 'Jenkins') {
                    sh '''
					eksctl create cluster --name udacitycluster --nodegroup-name standard-workers --node-type t2.small --nodes 2 --nodes-min 1 --nodes-max 3 --node-ami auto --region us-east-1
					'''
                }
            }
        }
        stage('Create conf file cluster') {
			steps {
				withAWS(region:'us-east-1', credentials: 'Jenkins') {
					sh '''
						aws eks --region us-east-1 update-kubeconfig --name udacitycluster
					'''
				}
			}
		}

    }
}